version: 0.2

phases:
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean install

  post_build:
    commands:
      - echo Building the Docker image...

artifacts:
  files:
    - target/diyo-service.jar
  discard-paths: yes